import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../../plans/logo-experiment.css'
import Navbar from '../components/Navbar'
import HtmlFooter from '../components/HtmlFooter'
import CookieBanner from '../components/CookieBanner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="nl">
      <body className={inter.className}>
        <Navbar />
        {children}
        <HtmlFooter />
+25 |         <CookieBanner />
      </body>
    </html>
  )
}
