import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../../plans/logo-experiment.css'
import Navbar from '../components/Navbar'
import HtmlFooter from '../components/HtmlFooter'
import CookieBanner from '../components/CookieBanner'
import WhatsAppButton from '../components/WhatsAppButton'
import { anniversaryConfig, isAnniversaryActive } from '../config/anniversary'
import JubileumPopup from '../components/JubileumPopup'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="nl">
      <body className={inter.className}>
        <Navbar />
        {children}
        <HtmlFooter />
        <CookieBanner />
        <WhatsAppButton />
        {isAnniversaryActive() && anniversaryConfig.showPopup && <JubileumPopup />}
      </body>
    </html>
  )
}
